# Generated by Django 3.1.5 on 2021-01-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='listStatus',
            field=models.CharField(choices=[('DO', 'Done'), ('TD', 'ToDo')], default='TD', max_length=2),
        ),
    ]
